version: "3"
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: beast
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: auth-app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
